
const cars = [
    {
        "Car_ID": 1,
        "Brand": "Toyota",
        "Model": "Corolla",
        "Year": 2018,
        "Kilometers_Driven": 50000,
        "Fuel_Type": "Petrol",
        "Transmission": "Manual",
        "Owner_Type": "First",
        "Mileage": 15,
        "Engine": 1498,
        "Power": 108,
        "Seats": 5,
        "Price": 800000
    },
    {
        "Car_ID": 2,
        "Brand": "Honda",
        "Model": "Civic",
        "Year": 2019,
        "Kilometers_Driven": 40000,
        "Fuel_Type": "Petrol",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 17,
        "Engine": 1597,
        "Power": 140,
        "Seats": 5,
        "Price": 1000000
    },
    {
        "Car_ID": 3,
        "Brand": "Ford",
        "Model": "Mustang",
        "Year": 2017,
        "Kilometers_Driven": 20000,
        "Fuel_Type": "Petrol",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 10,
        "Engine": 4951,
        "Power": 395,
        "Seats": 4,
        "Price": 2500000
    },
    {
        "Car_ID": 4,
        "Brand": "Maruti",
        "Model": "Swift",
        "Year": 2020,
        "Kilometers_Driven": 30000,
        "Fuel_Type": "Diesel",
        "Transmission": "Manual",
        "Owner_Type": "Third",
        "Mileage": 23,
        "Engine": 1248,
        "Power": 74,
        "Seats": 5,
        "Price": 600000
    },
    {
        "Car_ID": 5,
        "Brand": "Hyundai",
        "Model": "Sonata",
        "Year": 2016,
        "Kilometers_Driven": 60000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 18,
        "Engine": 1999,
        "Power": 194,
        "Seats": 5,
        "Price": 850000
    },
    {
        "Car_ID": 6,
        "Brand": "Tata",
        "Model": "Nexon",
        "Year": 2019,
        "Kilometers_Driven": 35000,
        "Fuel_Type": "Petrol",
        "Transmission": "Manual",
        "Owner_Type": "First",
        "Mileage": 17,
        "Engine": 1198,
        "Power": 108,
        "Seats": 5,
        "Price": 750000
    },
    {
        "Car_ID": 7,
        "Brand": "Mahindra",
        "Model": "Scorpio",
        "Year": 2018,
        "Kilometers_Driven": 45000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 15,
        "Engine": 2179,
        "Power": 140,
        "Seats": 7,
        "Price": 900000
    },
    {
        "Car_ID": 8,
        "Brand": "Volkswagen",
        "Model": "Polo",
        "Year": 2020,
        "Kilometers_Driven": 25000,
        "Fuel_Type": "Petrol",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 18,
        "Engine": 999,
        "Power": 76,
        "Seats": 5,
        "Price": 650000
    },
    {
        "Car_ID": 9,
        "Brand": "Audi",
        "Model": "A4",
        "Year": 2018,
        "Kilometers_Driven": 30000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 18,
        "Engine": 1968,
        "Power": 187,
        "Seats": 5,
        "Price": 2200000
    },
    {
        "Car_ID": 10,
        "Brand": "BMW",
        "Model": "X1",
        "Year": 2019,
        "Kilometers_Driven": 20000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 20,
        "Engine": 1995,
        "Power": 190,
        "Seats": 5,
        "Price": 2700000
    },
    {
        "Car_ID": 11,
        "Brand": "Mercedes",
        "Model": "C-Class",
        "Year": 2018,
        "Kilometers_Driven": 28000,
        "Fuel_Type": "Petrol",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 16,
        "Engine": 1991,
        "Power": 181,
        "Seats": 5,
        "Price": 2300000
    },
    {
        "Car_ID": 12,
        "Brand": "Ford",
        "Model": "Endeavour",
        "Year": 2017,
        "Kilometers_Driven": 35000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 12,
        "Engine": 2198,
        "Power": 158,
        "Seats": 7,
        "Price": 2000000
    },
    {
        "Car_ID": 13,
        "Brand": "Hyundai",
        "Model": "Creta",
        "Year": 2019,
        "Kilometers_Driven": 22000,
        "Fuel_Type": "Petrol",
        "Transmission": "Manual",
        "Owner_Type": "Third",
        "Mileage": 16,
        "Engine": 1497,
        "Power": 113,
        "Seats": 5,
        "Price": 850000
    },
    {
        "Car_ID": 14,
        "Brand": "Tata",
        "Model": "Harrier",
        "Year": 2018,
        "Kilometers_Driven": 40000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 17,
        "Engine": 1956,
        "Power": 167,
        "Seats": 5,
        "Price": 1600000
    },
    {
        "Car_ID": 15,
        "Brand": "Maruti",
        "Model": "Ertiga",
        "Year": 2020,
        "Kilometers_Driven": 18000,
        "Fuel_Type": "Petrol",
        "Transmission": "Manual",
        "Owner_Type": "First",
        "Mileage": 19,
        "Engine": 1462,
        "Power": 103,
        "Seats": 7,
        "Price": 850000
    },
    {
        "Car_ID": 16,
        "Brand": "Honda",
        "Model": "City",
        "Year": 2017,
        "Kilometers_Driven": 42000,
        "Fuel_Type": "Diesel",
        "Transmission": "Manual",
        "Owner_Type": "Second",
        "Mileage": 25,
        "Engine": 1498,
        "Power": 98,
        "Seats": 5,
        "Price": 650000
    },
    {
        "Car_ID": 17,
        "Brand": "Volkswagen",
        "Model": "Tiguan",
        "Year": 2018,
        "Kilometers_Driven": 32000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 17,
        "Engine": 1968,
        "Power": 141,
        "Seats": 5,
        "Price": 1800000
    },
    {
        "Car_ID": 18,
        "Brand": "Audi",
        "Model": "Q3",
        "Year": 2018,
        "Kilometers_Driven": 38000,
        "Fuel_Type": "Petrol",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 15,
        "Engine": 1395,
        "Power": 148,
        "Seats": 5,
        "Price": 1900000
    },
    {
        "Car_ID": 19,
        "Brand": "BMW",
        "Model": "5 Series",
        "Year": 2019,
        "Kilometers_Driven": 24000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 18,
        "Engine": 1995,
        "Power": 187,
        "Seats": 5,
        "Price": 3000000
    },
    {
        "Car_ID": 20,
        "Brand": "Mercedes",
        "Model": "GLC",
        "Year": 2017,
        "Kilometers_Driven": 26000,
        "Fuel_Type": "Petrol",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 12,
        "Engine": 1991,
        "Power": 241,
        "Seats": 5,
        "Price": 2500000
    },
    {
        "Car_ID": 21,
        "Brand": "Toyota",
        "Model": "Innova",
        "Year": 2018,
        "Kilometers_Driven": 50000,
        "Fuel_Type": "Diesel",
        "Transmission": "Manual",
        "Owner_Type": "First",
        "Mileage": 13,
        "Engine": 2755,
        "Power": 171,
        "Seats": 7,
        "Price": 1400000
    },
    {
        "Car_ID": 22,
        "Brand": "Ford",
        "Model": "Figo",
        "Year": 2020,
        "Kilometers_Driven": 15000,
        "Fuel_Type": "Petrol",
        "Transmission": "Manual",
        "Owner_Type": "Third",
        "Mileage": 18,
        "Engine": 1194,
        "Power": 94,
        "Seats": 5,
        "Price": 550000
    },
    {
        "Car_ID": 23,
        "Brand": "Hyundai",
        "Model": "Verna",
        "Year": 2019,
        "Kilometers_Driven": 26000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 24,
        "Engine": 1582,
        "Power": 126,
        "Seats": 5,
        "Price": 850000
    },
    {
        "Car_ID": 24,
        "Brand": "Tata",
        "Model": "Altroz",
        "Year": 2020,
        "Kilometers_Driven": 18000,
        "Fuel_Type": "Petrol",
        "Transmission": "Manual",
        "Owner_Type": "First",
        "Mileage": 20,
        "Engine": 1199,
        "Power": 85,
        "Seats": 5,
        "Price": 600000
    },
    {
        "Car_ID": 25,
        "Brand": "Mahindra",
        "Model": "Thar",
        "Year": 2021,
        "Kilometers_Driven": 10000,
        "Fuel_Type": "Diesel",
        "Transmission": "Manual",
        "Owner_Type": "First",
        "Mileage": 15,
        "Engine": 2184,
        "Power": 130,
        "Seats": 4,
        "Price": 1200000
    },
    {
        "Car_ID": 26,
        "Brand": "Volkswagen",
        "Model": "Passat",
        "Year": 2017,
        "Kilometers_Driven": 32000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 17,
        "Engine": 1968,
        "Power": 174,
        "Seats": 5,
        "Price": 1600000
    },
    {
        "Car_ID": 27,
        "Brand": "Audi",
        "Model": "A6",
        "Year": 2018,
        "Kilometers_Driven": 28000,
        "Fuel_Type": "Petrol",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 15,
        "Engine": 1984,
        "Power": 241,
        "Seats": 5,
        "Price": 3200000
    },
    {
        "Car_ID": 28,
        "Brand": "BMW",
        "Model": "X3",
        "Year": 2019,
        "Kilometers_Driven": 22000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 18,
        "Engine": 1995,
        "Power": 187,
        "Seats": 5,
        "Price": 2800000
    },
    {
        "Car_ID": 29,
        "Brand": "Mercedes",
        "Model": "E-Class",
        "Year": 2017,
        "Kilometers_Driven": 30000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "First",
        "Mileage": 16,
        "Engine": 1950,
        "Power": 191,
        "Seats": 5,
        "Price": 2700000
    },
    {
        "Car_ID": 30,
        "Brand": "Toyota",
        "Model": "Fortuner",
        "Year": 2018,
        "Kilometers_Driven": 38000,
        "Fuel_Type": "Diesel",
        "Transmission": "Automatic",
        "Owner_Type": "Second",
        "Mileage": 12,
        "Engine": 2755,
        "Power": 174,
        "Seats": 7,
        "Price": 2500000
    }
]


